#!/bin/bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

spawn_with_rules() {(
    # this rule also requires, that the client
    # sets the _NET_WM_PID property
    herbstclient rule once pid=$BASHPID maxage=10 "${RULES[@]}"
    exec "$@"
    ) &
}

hc emit_hook reload

#xsetroot -solid '#5A8E3A'
#xsetroot -solid 'lightblue'
xsetroot -solid '#191919'

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod1    # Use alt as the main modifier
#Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
#hc keybind $Mod-Return spawn xterm
hc keybind $Mod-Return spawn urxvtc

hc keybind $Mod-m spawn urxvtc -e ncmpcpp
hc keybind $Mod-n spawn urxvtc -e vim $HOME/notes/notes.txt

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
## ripped for Volumes
#hc keybind $Mod-Control-Left    resize left +$resizestep
#hc keybind $Mod-Control-Down    resize down +$resizestep
#hc keybind $Mod-Control-Up      resize up +$resizestep
#hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1 grid vertical horizontal
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
#hc keybind $Mod-p pseudotile toggle # run programs with mod-p 

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# tray toggle
hc keybind $Mod-t spawn ~/.config/herbstluftwm/tray.sh

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# running
hc keybind $Mod-p spawn dmenu_run

# lock the workstation
hc keybind $Mod-F12 spawn slock

# Volumes
hc keybind XF86AudioLowerVolume spawn ~/.config/herbstluftwm/volume.sh down
hc keybind XF86AudioRaiseVolume spawn ~/.config/herbstluftwm/volume.sh up
hc keybind XF86AudioMute spawn ~/.config/herbstluftwm/volume.sh mute
hc keybind $Mod-Control-Up spawn ~/.config/herbstluftwm/volume.sh up
hc keybind $Mod-Control-Down spawn ~/.config/herbstluftwm/volume.sh down


#// borders/gaps:
hc set always_show_frame 1
hc set frame_bg_transparent 0
hc set frame_border_width 2
hc set window_border_width 5
hc set window_border_inner_width 0
hc set gapless_grid 1
hc set frame_gap -2
hc set window_gap -2
hc set frame_padding 2
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
#// colors:
hc set frame_border_active_color '#101010'
hc set frame_border_normal_color '#101010'
hc set frame_bg_active_color '#202020'
hc set frame_bg_normal_color '#191919'
hc set window_border_active_color 'lightgreen'
#'#8f8f8f'
hc set window_border_normal_color '#161616'
hc set window_border_urgent_color '#4cdcd4'

# auto monitors
hc set auto_detect_monitors 1
# swap tag to monitor on which is pressed.
hc set swap_monitors_to_get_tag 1
# focus
hc set focus_follows_mouse 1

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule title="VMware Horizon View Client" tag=8 fullscreen=on index=01 pseudotile=on
hc rule title="Verbindung zu Server herstellen" tag=8 float=on index=00
hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule class~'(File-roller|file-roller)' float=on pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off
hc rule class~'(MPlayer|Vlc)' tag=3 fullscreen=on
hc rule class~'(Firefox|Chromium-browser|Google-chrome)' tag=2

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors


# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done

# layout
hc load 1 "(split horizontal:0.500000:0 (split vertical:0.700000:1 (clients vertical:0) (split horizontal:0.500000:1 (clients vertical:0) (clients vertical:0))) (clients vertical:0))"
hc spawn urxvtd -f
hc spawn xrdb -DSOLARIZED_LIGHT -merge ~/.Xdefaults
pgrep nm-applet || hc spawn nm-applet 

### Test for future use
## spawn an xterm with uname info, but not where the focus is
#RULES=( index='/' focus=off )
#spawn_with_rules xterm -e 'uname -a ; read'
#
## spawn an xterm in pseudotile mode
#RULES=( pseudotile=on focus=on )
#spawn_with_rules xterm
